version: '2.2'
services:
  postgres-betting-db:
    image: postgres:latest
    volumes:
      - ../common-deployment:/init-scripts
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: betting
      POSTGRES_PASSWORD: betting
    entrypoint: /init-scripts/init_psql.sh
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka 
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 
      KAFKA_CREATE_TOPICS: "test:1:1,market-projection:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock